Repository googleapis/nodejs-area120-tables, pull requests merged in 2020-11, with the labels that each got.

#14 fix: do not modify options object, use defaultScopes
  .github/workflows/ci.yaml
  .jsdoc.js
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  CODE_OF_CONDUCT.md
  README.md
  linkinator.config.json
  package.json
  src/index.ts
  src/v1alpha1/tables_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: automerge, cla: yes

#16 chore: give area120-tables push access
  .github/sync-repo-settings.yaml
Labels: cla: yes

#21 fix: better fallback feature detection, linting, use optional chaining for window.fetch feature detection, mark window as global for linter
  protos/protos.json
  src/v1alpha1/tables_service_client.ts
  synth.metadata
Labels: cla: yes, context: partial
