Repository googleapis/nodejs-area120-tables, pull requests merged in 2020-12, with the labels that each got.

#23 chore: generate GAPIC metadata JSON file
  src/v1alpha1/gapic_metadata.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#17 build: add codeowners file
  .github/CODEOWNERS
Labels: cla: yes

#25 docs: spelling correction, add instructions for authenticating for system tests
  CONTRIBUTING.md
  README.md
  synth.metadata
Labels: cla: yes, context: full
